# Generated by Django 3.1.5 on 2022-09-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=250)),
                ('about_course', models.TextField()),
                ('courseImg', models.ImageField(upload_to='static/img')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
