# Generated by Django 3.1.5 on 2022-09-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=250)),
                ('course_name', models.TextField()),
                ('studentImg', models.ImageField(upload_to='static/img')),
                ('marks', models.IntegerField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
