# Generated by Django 3.1.5 on 2022-09-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp', '0003_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=250)),
                ('stu_course', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=250)),
                ('query', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campus',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
