# Generated by Django 3.1.5 on 2022-09-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp', '0004_auto_20220914_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
