# Generated by Django 3.1.5 on 2022-09-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp', '0006_team_memberimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('StuImg', models.ImageField(upload_to='static/img')),
                ('fullName', models.CharField(max_length=250)),
                ('Message', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
